### PR TITLE
WIP: An alternative color table representation

### PR DESCRIPTION
**Pull request by hjmjohnson**
This is a more exhausitve color table representation from
the X11 org.  The license is clear that this can be share.

This needs further revew before inclusion, and probably
should not be included in it's current state.

### CODE REVIEW

**Comment by fbbdev** [comment]
@hjmjohnson is this really necessary? I mean, these are the same colors contained in `colors.hpp` plus a lot of intermediate shades... people can create them as needed. I could add [SASS-style](http://jackiebalzer.com/color) color manipulators to make it easier (e.g. `mix`, `lighten`, `darken`, etc.).

**Comment by fbbdev** [comment]
Having a color table is useful, but I don't see the benefit of having such a large table.

**Comment by hjmjohnson** [comment]
OK.  I just looked for a standard definition that xterm folks might be used to.  This is the color pallette from X11, so I thought it matched well with terminal color choosing.

Cognitively I prefer picking "Red" to {1.0f, 0.0f, 0.0f}, and when choosing colors, I immediately know what aquamarine is, but I have no idea what the tuple would be.

**Comment by fbbdev** [comment]
Having a default color palette included in the library was definitely on my radar; indeed, I promoted to [library header](https://github.com/fbbdev/plot/blob/master/colors.hpp) the file `opengl_colors.hpp` you included with #17, so you can use `plot::palette::red` and the like, as demonstrated in [`canvas.cpp`](https://github.com/fbbdev/plot/blob/master/examples/canvas.cpp)

My point is, I had a look at the X11 palette and it's almost identical to the one you provided earlier, plus some additional shades, like aquamarine1, aquamarine2, gray1, gray2, gray3 and so on, so I don't think it's a valuable addition. That's all :)

**Comment by hjmjohnson** [comment]
I agree.  My only thought was the "opengl" color pallette was the first one I found.  I latter found the X11 pallette, and i'm 90% sure it is a superset of the opengl pallette.  

Since it was trivial to have expanded color pallette, I just provided it for your consideration.

I'm happy either way.

Hans

**Pull request closed without merging**
